import 'dart:convert';

/// What the user was doing while a step was counted.
///
/// Stored per minute alongside the step count, so the history chart can colour
/// each day by how those steps were earned.
enum Activity {
  unknown('unknown'),
  still('still'),
  walking('walking'),
  running('running'),
  stairsUp('stairs_up'),
  stairsDown('stairs_down'),
  vehicle('vehicle');

  const Activity(this.id);

  /// Stable database identifier. Never derive this from [name] — renaming an
  /// enum value would silently orphan every stored row.
  final String id;

  static Activity fromId(String id) =>
      Activity.values.firstWhere((a) => a.id == id, orElse: () => Activity.unknown);

  /// Activities that actually contribute steps. Still and vehicle never do,
  /// by construction, but stored data can always surprise you.
  bool get countsSteps =>
      this == walking || this == running || this == stairsUp || this == stairsDown;

  bool get isStairs => this == stairsUp || this == stairsDown;

  String get label => switch (this) {
        Activity.unknown => 'Unclassified',
        Activity.still => 'Still',
        Activity.walking => 'Walking',
        Activity.running => 'Running',
        Activity.stairsUp => 'Stairs up',
        Activity.stairsDown => 'Stairs down',
        Activity.vehicle => 'Vehicle',
      };
}

/// Tunable thresholds for [ActivityClassifier].
///
/// Deliberately shaped like [CalibrationParams] — same clamping, same JSON, same
/// generic field access — so the existing coordinate-descent optimiser can tune
/// these without knowing anything about activities.
class ActivityParams {
  const ActivityParams({
    this.stillAccelSigmaMax = 0.15,
    this.vehicleGyroMax = 0.03,
    this.runningCadenceMin = 140,
    this.runningFlightMax = 5.0,
    this.runningAmplitudeMin = 8.0,
    this.stairsAltitudeRateMin = 0.08,
    this.stairsMinDurationMs = 2500,
  });

  /// Below this band-passed standard deviation the device is not moving.
  final double stillAccelSigmaMax;

  /// Rotational energy below this, with acceleration present, means the motion
  /// is being transmitted through a vehicle rather than generated by a body.
  final double vehicleGyroMax;

  /// Steps per minute. A brisk walk reaches ~140, so cadence alone cannot
  /// separate walking from a slow jog — it is necessary, not sufficient.
  final double runningCadenceMin;

  /// Minimum acceleration magnitude, in m/s², seen during the window.
  ///
  /// This is the decisive running signal. Running has a flight phase where both
  /// feet leave the ground and the device approaches freefall, so |a| dips far
  /// below gravity. Walking always keeps one foot planted and never does.
  final double runningFlightMax;

  /// Fallback for runners whose phone damps the flight dip (bags, loose
  /// pockets): a hard impact amplitude combined with high cadence.
  ///
  /// Band-passed peak-to-trough, in m/s². Ordinary walking sits near 4 and
  /// running near 20, so this has to stay well clear of 4 — set too low it
  /// reclassifies every brisk walk as a run, since a brisk walk also clears
  /// the cadence threshold.
  final double runningAmplitudeMin;

  /// Vertical speed in m/s. Stairs are climbed at roughly 0.2-0.3 m/s; weather
  /// drift moves the barometer some four orders of magnitude slower, so this
  /// threshold has enormous headroom.
  final double stairsAltitudeRateMin;

  /// How long the vertical motion must persist. Stops a door opening or a gust
  /// of wind past a pressure port from registering as a flight of stairs.
  final int stairsMinDurationMs;

  static const ActivityParams factory = ActivityParams();

  static const Map<String, (double, double)> bounds = {
    'stillAccelSigmaMax': (0.02, 0.6),
    'vehicleGyroMax': (0.005, 0.15),
    'runningCadenceMin': (110, 190),
    'runningFlightMax': (1.0, 8.0),
    'runningAmplitudeMin': (3.0, 20.0),
    'stairsAltitudeRateMin': (0.03, 0.30),
    'stairsMinDurationMs': (1000, 6000),
  };

  static const List<String> tunableKeys = [
    'stairsAltitudeRateMin',
    'runningFlightMax',
    'runningCadenceMin',
    'runningAmplitudeMin',
    'stairsMinDurationMs',
    'stillAccelSigmaMax',
    'vehicleGyroMax',
  ];

  static double _clamp(String key, double v) {
    final b = bounds[key]!;
    return v.clamp(b.$1, b.$2).toDouble();
  }

  ActivityParams clamped() => ActivityParams(
        stillAccelSigmaMax: _clamp('stillAccelSigmaMax', stillAccelSigmaMax),
        vehicleGyroMax: _clamp('vehicleGyroMax', vehicleGyroMax),
        runningCadenceMin: _clamp('runningCadenceMin', runningCadenceMin),
        runningFlightMax: _clamp('runningFlightMax', runningFlightMax),
        runningAmplitudeMin: _clamp('runningAmplitudeMin', runningAmplitudeMin),
        stairsAltitudeRateMin:
            _clamp('stairsAltitudeRateMin', stairsAltitudeRateMin),
        stairsMinDurationMs:
            _clamp('stairsMinDurationMs', stairsMinDurationMs.toDouble()).round(),
      );

  ActivityParams copyWith({
    double? stillAccelSigmaMax,
    double? vehicleGyroMax,
    double? runningCadenceMin,
    double? runningFlightMax,
    double? runningAmplitudeMin,
    double? stairsAltitudeRateMin,
    int? stairsMinDurationMs,
  }) =>
      ActivityParams(
        stillAccelSigmaMax: stillAccelSigmaMax ?? this.stillAccelSigmaMax,
        vehicleGyroMax: vehicleGyroMax ?? this.vehicleGyroMax,
        runningCadenceMin: runningCadenceMin ?? this.runningCadenceMin,
        runningFlightMax: runningFlightMax ?? this.runningFlightMax,
        runningAmplitudeMin: runningAmplitudeMin ?? this.runningAmplitudeMin,
        stairsAltitudeRateMin:
            stairsAltitudeRateMin ?? this.stairsAltitudeRateMin,
        stairsMinDurationMs: stairsMinDurationMs ?? this.stairsMinDurationMs,
      );

  double operator [](String key) => switch (key) {
        'stillAccelSigmaMax' => stillAccelSigmaMax,
        'vehicleGyroMax' => vehicleGyroMax,
        'runningCadenceMin' => runningCadenceMin,
        'runningFlightMax' => runningFlightMax,
        'runningAmplitudeMin' => runningAmplitudeMin,
        'stairsAltitudeRateMin' => stairsAltitudeRateMin,
        'stairsMinDurationMs' => stairsMinDurationMs.toDouble(),
        _ => throw ArgumentError('unknown activity parameter: $key'),
      };

  ActivityParams withField(String key, double value) => switch (key) {
        'stillAccelSigmaMax' => copyWith(stillAccelSigmaMax: value),
        'vehicleGyroMax' => copyWith(vehicleGyroMax: value),
        'runningCadenceMin' => copyWith(runningCadenceMin: value),
        'runningFlightMax' => copyWith(runningFlightMax: value),
        'runningAmplitudeMin' => copyWith(runningAmplitudeMin: value),
        'stairsAltitudeRateMin' => copyWith(stairsAltitudeRateMin: value),
        'stairsMinDurationMs' => copyWith(stairsMinDurationMs: value.round()),
        _ => throw ArgumentError('unknown activity parameter: $key'),
      }
          .clamped();

  Map<String, dynamic> toMap() => {
        'stillAccelSigmaMax': stillAccelSigmaMax,
        'vehicleGyroMax': vehicleGyroMax,
        'runningCadenceMin': runningCadenceMin,
        'runningFlightMax': runningFlightMax,
        'runningAmplitudeMin': runningAmplitudeMin,
        'stairsAltitudeRateMin': stairsAltitudeRateMin,
        'stairsMinDurationMs': stairsMinDurationMs,
      };

  factory ActivityParams.fromMap(Map<String, dynamic> m) => ActivityParams(
        stillAccelSigmaMax: (m['stillAccelSigmaMax'] as num?)?.toDouble() ??
            factory.stillAccelSigmaMax,
        vehicleGyroMax:
            (m['vehicleGyroMax'] as num?)?.toDouble() ?? factory.vehicleGyroMax,
        runningCadenceMin: (m['runningCadenceMin'] as num?)?.toDouble() ??
            factory.runningCadenceMin,
        runningFlightMax: (m['runningFlightMax'] as num?)?.toDouble() ??
            factory.runningFlightMax,
        runningAmplitudeMin: (m['runningAmplitudeMin'] as num?)?.toDouble() ??
            factory.runningAmplitudeMin,
        stairsAltitudeRateMin: (m['stairsAltitudeRateMin'] as num?)?.toDouble() ??
            factory.stairsAltitudeRateMin,
        stairsMinDurationMs: (m['stairsMinDurationMs'] as num?)?.toInt() ??
            factory.stairsMinDurationMs,
      ).clamped();

  String toJson() => jsonEncode(toMap());

  factory ActivityParams.fromJson(String s) =>
      ActivityParams.fromMap(jsonDecode(s) as Map<String, dynamic>);

  @override
  bool operator ==(Object other) =>
      other is ActivityParams &&
      other.stillAccelSigmaMax == stillAccelSigmaMax &&
      other.vehicleGyroMax == vehicleGyroMax &&
      other.runningCadenceMin == runningCadenceMin &&
      other.runningFlightMax == runningFlightMax &&
      other.runningAmplitudeMin == runningAmplitudeMin &&
      other.stairsAltitudeRateMin == stairsAltitudeRateMin &&
      other.stairsMinDurationMs == stairsMinDurationMs;

  @override
  int get hashCode => Object.hash(
      stillAccelSigmaMax,
      vehicleGyroMax,
      runningCadenceMin,
      runningFlightMax,
      runningAmplitudeMin,
      stairsAltitudeRateMin,
      stairsMinDurationMs);

  @override
  String toString() => 'ActivityParams(${toMap()})';
}
